version: '3.7'
services: 
  redis:
    image: redis:latest
    env_file:
      - .env
    restart: always
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_INTERNAL_PORT}
    volumes:
      - type: volume
        source: redis-volume
        target: /data
    networks:
      - comp7940
  api-server: 
    image: api-server
    build:
      context: ./apis
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment: 
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_INTERNAL_PORT}
    restart: always
    container_name: api-server
    depends_on: 
      - redis
    networks:
      - comp7940
  chatbot1: 
    image: chatbot
    build:
      context: ./chatbot
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment: 
      - TELEGRAM_ACCESS_TOKEN=${TELEGRAM_ACCESS_TOKEN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_INTERNAL_PORT}
      - CHATGPT_BASICURL=${CHATGPT_BASICURL}
      - CHATGPT_MODELNAME=${CHATGPT_MODELNAME}
      - CHATGPT_APIVERSION=${CHATGPT_APIVERSION}
      - CHATGPT_ACCESS_TOKEN=${CHATGPT_ACCESS_TOKEN}
      - SECRET_TOKEN=${SECRET_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - LOCALHOST=0.0.0.0
      - LISTEN_PORT=5000
      - URL_PATH=1
      - CERT_PATH=nginx-selfsigned.crt
    restart: always
    container_name: chatbot1
    depends_on: 
      - redis
      - api-server
    networks:
      - comp7940
  chatbot2: 
    image: chatbot
    env_file:
      - .env
    environment: 
      - TELEGRAM_ACCESS_TOKEN=${TELEGRAM_ACCESS_TOKEN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_INTERNAL_PORT}
      - CHATGPT_BASICURL=${CHATGPT_BASICURL}
      - CHATGPT_MODELNAME=${CHATGPT_MODELNAME}
      - CHATGPT_APIVERSION=${CHATGPT_APIVERSION}
      - CHATGPT_ACCESS_TOKEN=${CHATGPT_ACCESS_TOKEN}
      - SECRET_TOKEN=${SECRET_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - LOCALHOST=0.0.0.0
      - LISTEN_PORT=5001
      - URL_PATH=1
      - CERT_PATH=nginx-selfsigned.crt
    restart: always
    container_name: chatbot2
    depends_on: 
      - redis
      - api-server
      - chatbot1
    networks:
      - comp7940
  redis-commander:
    image: rediscommander/redis-commander:latest
    env_file:
      - .env
    depends_on:
      - redis
    restart: always
    container_name: redis-commander
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - HTTP_USER=${REDIS_HTTP_USER}
      - HTTP_PASSWORD=${REDIS_PASSWORD}
    networks:
      - comp7940
  nginx: 
    image: nginx-project
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - "443:443"
      - "80:80"
    restart: always
    container_name: nginx
    volumes: 
      - /home/nginx/log:/var/log/nginx
    networks:
      - comp7940
    depends_on: 
      - redis-commander
      - api-server
      - chatbot1
      - chatbot2

networks:
  comp7940:
    driver: bridge

volumes:
  redis-volume: